version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quan-ly-thu-vien-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quan-ly-thu-vien-dev
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: quan-ly-thu-vien-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8001:8001'
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
